# Generated by Django 2.2.6 on 2019-10-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
