# Generated by Django 2.2.6 on 2019-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_scrapedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedate',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
